version: 3.0.0.{build}
image: Visual Studio 2022

environment:
  NODE_VERSION: 18

install:
  - ps: Install-Product node $env:NODE_VERSION

build_script:
  - npm install
  - npm run dist

artifacts:
  - path: dist\*
    name: installer